# Generated by Django 3.2.7 on 2021-10-12 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('N', 'None'), ('A', 'Active'), ('D', 'Done')], default='A', max_length=1)),
                ('created', models.DateTimeField()),
                ('edited', models.DateTimeField()),
                ('due', models.DateTimeField()),
                ('reminder', models.IntegerField()),
                ('flags', models.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
