apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  DB_NAME: db_name_in_base_64_encoding
  DB_PORT: db_port_in_base_64_encoding
  DB_HOST: db_host_in_base_64_encoding
  SECRET_KEY: secret_key_in_base_64_encoding