apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
        - name: mongodatabase
          image: mongo
          tty: true
          ports:
            - containerPort: 27017
          envFrom:
            - secretRef:
                name: mongo-secret
        - name: django
          image: clistenesfernandes/todoproject
          tty: true
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: mongo-secret
          lifecycle:
            postStart:
              exec:
                command: [ "/bin/sh", "-c", "python manage.py migrate" ]

